#line 2 "prep_scanner.c"

#line 4 "prep_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 116
#define YY_END_OF_BUFFER 117
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[311] =
    {   0,
        0,    0,  117,  115,  110,  112,  111,   57,   61,   39,
       35,   44,   45,   46,   33,   31,   59,   32,   60,   34,
        3,    3,   55,   58,   40,   30,   41,   56,  113,  113,
       49,   51,   50,   37,   43,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,   47,   36,   48,   38,   22,    0,   42,    0,
       16,   23,   17,    0,    0,   53,   14,   10,   12,   11,
       13,   20,    6,   52,   54,   15,    7,    2,    0,    3,
        0,    3,   25,   27,   29,   21,   28,   26,  113,  113,
        0,   19,  113,  113,  113,  113,  113,  113,   73,  113,

      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
       62,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,   18,   24,
        0,   42,    0,    4,    0,    6,    6,    0,    7,    2,
        0,    5,    1,    8,    9,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,   65,  113,  113,  113,   79,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,    0,    6,
        0,    6,    0,    7,    5,    1,   66,  113,  113,   68,

       69,  113,  113,  113,  113,   63,   75,   87,  113,  113,
      113,   91,  113,  113,  113,   92,   78,   96,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,   88,  113,  113,  113,  108,  113,  113,    0,
        6,   67,  113,   70,  113,  113,  113,  113,   89,  113,
       77,   82,  113,  113,  113,  113,  113,  113,   99,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  106,
      113,  113,   64,   95,  113,  113,   74,   76,   83,  113,
       94,   93,   80,  113,   98,  100,  101,  102,   86,   85,
      103,  104,   84,  113,  113,  113,  113,  113,   72,   81,

      113,   90,  105,  113,  113,   71,   97,  107,  109,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   29,   47,   48,   49,   50,
       51,   52,   29,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    4,    4,
        4,    4,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[316] =
    {   0,
        0,    0,  189,  977,  977,  977,  977,  163,   60,  159,
       59,  146,  977,  977,   51,   56,  977,   57,   52,   61,
       79,   72,  977,  977,   53,  147,   62,  977,   74,   98,
      977,  977,  977,  145,  977,   86,   94,  105,  107,   82,
      115,  118,  121,  100,  143,  126,  154,  156,  159,  165,
      169,  172,  977,   66,  977,  977,  977,   81,  977,  189,
      977,  977,  977,   74,  143,  977,  977,  977,  977,  977,
      977,  977,  179,  977,  977,  977,  206,  210,  232,  208,
        0,  241,  142,  977,  977,  977,  977,  131,  175,  181,
       88,  977,  212,  243,  225,  256,  185,  258,  251,  262,

      268,  272,  274,  277,  280,  284,  286,  290,  292,  294,
      296,  301,  310,  314,  318,  322,  326,  332,  334,  336,
      339,  345,  347,  353,  358,  361,  368,  372,  977,  977,
      125,  142,  390,  977,  379,  977,  393,  387,  977,  395,
      409,  412,  402,  977,  977,  419,  426,  428,  430,  434,
      438,  443,  447,  449,  455,  459,  461,  464,  466,  470,
      477,  479,  481,  483,  487,  489,  491,  493,  501,  504,
      506,  513,  515,  517,  523,  520,  525,  527,  529,  532,
      534,  536,  546,  542,  550,  556,  563,  558,  571,  580,
      594,  977,  573,  586,  977,  587,  576,  584,  601,  603,

      606,  608,  614,  618,  620,  622,  626,  628,  630,  635,
      632,  637,  639,  643,  646,  648,  651,  653,  657,  660,
      662,  666,  669,  671,  673,  679,  681,  685,  688,  691,
      693,  695,  700,  705,  714,  721,  723,  725,  730,  732,
      738,  734,  736,  740,  742,  751,  755,  744,  759,  764,
      766,  769,  771,  777,  782,  784,  786,  789,  791,  793,
      795,  800,  797,  802,  804,  806,  811,  813,  824,  817,
      826,  828,  834,  838,  845,  849,  851,  853,  859,  862,
      864,  866,  868,  870,  872,  874,  876,  878,  880,  884,
      888,  890,  892,  895,  897,  899,  901,  903,  905,  907,

      909,  911,  913,  915,  917,  919,  924,  928,  932,  977,
      962,  966,  968,  972,   93
    } ;

static yyconst flex_int16_t yy_def[316] =
    {   0,
      310,    1,  310,  310,  310,  310,  310,  310,  311,  310,
      310,  312,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  313,  313,
      310,  310,  310,  310,  310,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  310,  310,  310,  310,  310,  311,  310,  314,
      310,  310,  310,  312,  312,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      315,  310,  310,  310,  310,  310,  310,  310,  313,  313,
      312,  310,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  310,  310,
      311,  311,  314,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  315,  310,  310,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  310,  310,
      310,  310,  310,  310,  310,  310,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  310,
      310,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,    0,
      310,  310,  310,  310,  310
    } ;

static yyconst flex_int16_t yy_nxt[1043] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   29,   30,
       29,   29,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   29,   43,   29,   44,   45,   29,
       29,   46,   47,   48,   49,   50,   51,   52,   29,   29,
       29,   53,   54,   55,   56,   59,   62,   66,   68,   73,
       73,   70,   74,   67,   83,   84,   85,   75,   69,   71,
       72,   63,  134,   76,   87,   88,   59,   77,  129,   82,
       82,   89,   89,   60,   77,  143,   78,   78,   79,   89,

       89,   80,   80,   89,   89,   79,   91,   65,   80,   80,
       81,   89,   89,   79,   60,   89,   89,   89,   89,   80,
       79,   65,   89,   89,   89,   89,   80,   80,  130,  100,
       59,  101,   89,   89,   80,   89,   89,   81,   89,   89,
      102,   93,   95,   89,   89,  310,   94,   59,   98,   96,
      113,   64,  103,  145,  104,   97,  105,   99,   60,  109,
       89,   89,  106,  111,  144,  107,  108,   92,  110,   86,
      112,   89,   89,   89,   89,   60,   89,   89,  116,   65,
      114,   61,   89,   89,  115,   57,   89,   89,  310,   89,
       89,   58,   89,   89,  132,  117,   73,   73,   89,   89,

      118,  119,   89,   89,  310,  135,  136,  310,  136,  123,
      120,  124,  310,  121,  126,  122,  128,  310,  125,  127,
      135,  136,  133,  137,  137,   77,  136,   78,   78,   89,
       89,  310,  138,  139,  151,  139,   79,   80,   80,  140,
      140,  310,   89,   89,  141,  310,  141,  138,  139,  142,
      142,   79,  310,  139,  310,   80,   77,  140,   82,   82,
       89,   89,  310,   80,  310,  140,  146,   79,   89,   89,
       80,   80,  148,   89,   89,   89,   89,  310,  149,   89,
       89,  310,   79,  310,  147,   89,   89,  310,   80,   89,
       89,   89,   89,  150,   89,   89,   80,   89,   89,  310,

      152,   89,   89,   89,   89,  310,  153,   89,   89,   89,
       89,   89,   89,   89,   89,  154,  310,  156,   89,   89,
      310,  158,  310,  155,  159,  310,  157,   89,   89,  310,
      160,   89,   89,  310,  161,   89,   89,  162,  163,   89,
       89,  310,  164,   89,   89,  310,  165,  310,  166,   89,
       89,   89,   89,   89,   89,  167,   89,   89,  310,  168,
      310,  169,   89,   89,   89,   89,  170,  171,  310,  172,
       89,   89,  310,  177,  310,   89,   89,  175,   89,   89,
      173,  310,  174,  310,  179,   89,   89,  310,  178,   89,
       89,  189,   58,  189,  176,  132,  190,  190,  180,  193,

      310,  193,  181,  310,  194,  194,  184,  310,  182,  183,
      137,  137,  310,  186,  185,  187,  310,  188,  310,  191,
      192,  310,  192,  133,  140,  140,  142,  142,  310,  142,
      142,  196,  196,  310,  191,  192,   89,   89,  310,  195,
      192,  195,  140,   89,   89,   89,   89,   89,   89,  196,
      140,   89,   89,  310,  195,   89,   89,  196,  310,  195,
       89,   89,  310,  198,   89,   89,   89,   89,  310,  197,
      310,  200,   89,   89,  310,  199,   89,   89,   89,   89,
      204,   89,   89,   89,   89,  205,  201,   89,   89,  310,
      206,  202,  203,  310,   89,   89,   89,   89,   89,   89,

       89,   89,  209,  207,   89,   89,   89,   89,   89,   89,
       89,   89,  212,  208,  213,  310,  211,  210,   89,   89,
      214,   89,   89,   89,   89,  310,  216,  310,  215,  310,
       89,   89,   89,   89,   89,   89,  218,   89,   89,  217,
       89,   89,   89,   89,   89,   89,   89,   89,  219,   89,
       89,   89,   89,   89,   89,  221,  310,  220,  222,   89,
       89,  226,  310,   89,   89,  310,  228,   89,   89,  224,
      223,  310,  225,   89,   89,   89,   89,  233,  310,  227,
       89,   89,  229,  230,  310,  232,  231,  234,  190,  190,
      194,  194,  235,   89,   89,  236,  237,  190,  190,  310,

      238,   89,   89,  194,  194,  239,  240,  136,  240,  136,
      310,  241,  241,  139,  310,  139,  196,  196,   89,   89,
       89,   89,  136,   89,   89,   89,   89,  136,  139,  310,
      242,   89,   89,  139,  196,   89,   89,   89,   89,   89,
       89,  310,  196,   89,   89,   89,   89,   89,   89,   89,
       89,  243,   89,   89,   89,   89,   89,   89,  310,  245,
       89,   89,  244,   89,   89,   89,   89,  247,   89,   89,
       89,   89,  310,  246,   89,   89,  249,   89,   89,   89,
       89,  310,  248,   89,   89,  250,   89,   89,   89,   89,
       89,   89,  252,  251,  310,  253,   89,   89,   89,   89,

      310,  255,   89,   89,  310,   89,   89,  254,   89,   89,
       89,   89,   89,   89,  260,  310,  256,   89,   89,  257,
      310,  258,   89,   89,  310,  259,  262,  265,  310,  261,
      266,   89,   89,  263,  267,  310,  264,  310,   89,   89,
       89,   89,   89,   89,  310,  269,  268,   89,   89,  241,
      241,   89,   89,   89,   89,  241,  241,   89,   89,   89,
       89,   89,   89,  270,  271,  192,  310,  192,   89,   89,
      310,  273,   89,   89,  310,  274,   89,   89,  310,  272,
      192,   89,   89,   89,   89,  192,   89,   89,   89,   89,
      310,  275,  310,  278,   89,   89,  277,  310,  276,   89,

       89,   89,   89,   89,   89,  279,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,  281,   89,   89,   89,
       89,   89,   89,   89,   89,  280,  283,  310,   89,   89,
       89,   89,  310,  286,   89,   89,  282,  287,  285,  288,
      284,   89,   89,   89,   89,   89,   89,  310,  289,  310,
      292,   89,   89,  310,  294,   89,   89,  310,  291,  293,
      310,  290,   89,   89,  310,  295,   89,   89,   89,   89,
       89,   89,  310,  297,  310,  296,   89,   89,  310,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,  310,

      298,   89,   89,  299,  300,   89,   89,   89,   89,   89,
       89,  301,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,  310,  303,
      304,   89,   89,  310,  306,   89,   89,  302,  305,   89,
       89,  310,  310,  310,  310,  308,  310,  310,  309,  310,
      310,  307,   58,   58,   58,   58,   64,  310,   64,   64,
       90,   90,  131,  131,  131,  131,    3,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,

      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310
    } ;

static yyconst flex_int16_t yy_chk[1043] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    9,   11,   15,   16,   19,
       19,   18,   20,   15,   25,   25,   25,   20,   16,   18,
       18,   11,   64,   20,   27,   27,   58,   22,   54,   22,
       22,   29,   29,    9,   21,  315,   21,   21,   22,   40,

       40,   22,   22,   36,   36,   21,   30,   64,   21,   21,
       21,   37,   37,   22,   58,   30,   30,   44,   44,   22,
       21,   91,   38,   38,   39,   39,   21,   22,   54,   40,
      131,   40,   41,   41,   21,   42,   42,   21,   43,   43,
       40,   36,   38,   46,   46,   65,   37,  132,   39,   38,
       44,   65,   41,   88,   41,   38,   41,   39,  131,   42,
       45,   45,   41,   43,   83,   41,   41,   34,   42,   26,
       43,   47,   47,   48,   48,  132,   49,   49,   46,   12,
       45,   10,   50,   50,   45,    8,   51,   51,    3,   52,
       52,   60,   89,   89,   60,   47,   73,   73,   90,   90,

       48,   48,   97,   97,    0,   73,   73,    0,   73,   49,
       48,   49,    0,   48,   50,   48,   52,    0,   49,   51,
       73,   73,   60,   77,   77,   78,   73,   78,   78,   93,
       93,    0,   77,   77,   97,   77,   78,   80,   80,   78,
       78,    0,   95,   95,   79,    0,   79,   77,   77,   79,
       79,   78,    0,   77,    0,   80,   82,   78,   82,   82,
       94,   94,    0,   80,    0,   78,   93,   82,   99,   99,
       82,   82,   95,   96,   96,   98,   98,    0,   95,  100,
      100,    0,   82,    0,   94,  101,  101,    0,   82,  102,
      102,  103,  103,   96,  104,  104,   82,  105,  105,    0,

       98,  106,  106,  107,  107,    0,   99,  108,  108,  109,
      109,  110,  110,  111,  111,  100,    0,  102,  112,  112,
        0,  103,    0,  101,  104,    0,  102,  113,  113,    0,
      105,  114,  114,    0,  106,  115,  115,  107,  107,  116,
      116,    0,  108,  117,  117,    0,  109,    0,  110,  118,
      118,  119,  119,  120,  120,  112,  121,  121,    0,  113,
        0,  114,  122,  122,  123,  123,  115,  116,    0,  117,
      124,  124,    0,  120,    0,  125,  125,  119,  126,  126,
      117,    0,  118,    0,  121,  127,  127,    0,  120,  128,
      128,  135,  133,  135,  119,  133,  135,  135,  122,  138,

        0,  138,  123,    0,  138,  138,  126,    0,  124,  125,
      137,  137,    0,  127,  126,  127,    0,  128,    0,  137,
      137,    0,  137,  133,  140,  140,  141,  141,    0,  142,
      142,  143,  143,    0,  137,  137,  146,  146,    0,  142,
      137,  142,  140,  147,  147,  148,  148,  149,  149,  143,
      140,  150,  150,    0,  142,  151,  151,  143,    0,  142,
      152,  152,    0,  147,  153,  153,  154,  154,    0,  146,
        0,  149,  155,  155,    0,  148,  156,  156,  157,  157,
      152,  158,  158,  159,  159,  153,  150,  160,  160,    0,
      154,  151,  151,    0,  161,  161,  162,  162,  163,  163,

      164,  164,  157,  155,  165,  165,  166,  166,  167,  167,
      168,  168,  160,  156,  161,    0,  159,  158,  169,  169,
      162,  170,  170,  171,  171,    0,  165,    0,  164,    0,
      172,  172,  173,  173,  174,  174,  168,  176,  176,  166,
      175,  175,  177,  177,  178,  178,  179,  179,  169,  180,
      180,  181,  181,  182,  182,  171,    0,  170,  172,  184,
      184,  176,    0,  183,  183,    0,  178,  185,  185,  174,
      173,    0,  175,  186,  186,  188,  188,  182,    0,  177,
      187,  187,  178,  179,    0,  181,  180,  183,  189,  189,
      193,  193,  184,  197,  197,  185,  186,  190,  190,    0,

      187,  198,  198,  194,  194,  188,  191,  190,  191,  190,
        0,  191,  191,  194,    0,  194,  196,  196,  199,  199,
      200,  200,  190,  201,  201,  202,  202,  190,  194,    0,
      198,  203,  203,  194,  196,  204,  204,  205,  205,  206,
      206,    0,  196,  207,  207,  208,  208,  209,  209,  211,
      211,  199,  210,  210,  212,  212,  213,  213,    0,  203,
      214,  214,  202,  215,  215,  216,  216,  205,  217,  217,
      218,  218,    0,  204,  219,  219,  210,  220,  220,  221,
      221,    0,  209,  222,  222,  211,  223,  223,  224,  224,
      225,  225,  214,  213,    0,  215,  226,  226,  227,  227,

        0,  220,  228,  228,    0,  229,  229,  219,  230,  230,
      231,  231,  232,  232,  225,    0,  221,  233,  233,  222,
        0,  223,  234,  234,    0,  224,  227,  229,    0,  226,
      230,  235,  235,  228,  231,    0,  228,    0,  236,  236,
      237,  237,  238,  238,    0,  234,  232,  239,  239,  240,
      240,  242,  242,  243,  243,  241,  241,  244,  244,  245,
      245,  248,  248,  235,  236,  241,    0,  241,  246,  246,
        0,  239,  247,  247,    0,  243,  249,  249,    0,  238,
      241,  250,  250,  251,  251,  241,  252,  252,  253,  253,
        0,  245,    0,  248,  254,  254,  247,    0,  246,  255,

      255,  256,  256,  257,  257,  250,  258,  258,  259,  259,
      260,  260,  261,  261,  263,  263,  254,  262,  262,  264,
      264,  265,  265,  266,  266,  253,  256,    0,  267,  267,
      268,  268,    0,  260,  270,  270,  255,  261,  258,  262,
      257,  269,  269,  271,  271,  272,  272,    0,  263,    0,
      266,  273,  273,    0,  268,  274,  274,    0,  265,  267,
        0,  264,  275,  275,    0,  269,  276,  276,  277,  277,
      278,  278,    0,  272,    0,  271,  279,  279,    0,  280,
      280,  281,  281,  282,  282,  283,  283,  284,  284,  285,
      285,  286,  286,  287,  287,  288,  288,  289,  289,    0,

      275,  290,  290,  276,  280,  291,  291,  292,  292,  293,
      293,  284,  294,  294,  295,  295,  296,  296,  297,  297,
      298,  298,  299,  299,  300,  300,  301,  301,  302,  302,
      303,  303,  304,  304,  305,  305,  306,  306,    0,  295,
      296,  307,  307,    0,  298,  308,  308,  294,  297,  309,
      309,    0,    0,    0,    0,  304,    0,    0,  305,    0,
        0,  301,  311,  311,  311,  311,  312,    0,  312,  312,
      313,  313,  314,  314,  314,  314,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,

      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[117] =
    {   0,
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 6 "scanner.l"
	#include <stdio.h>
	#include <ctype.h>
	#include "global.h"
	char name[512] = "";
	int insertedTokens = 0;
	int palabras_reservadas = 0;
	int identifiers = 0;
	int literals = 0;
	int operators = 0;
	int delimiters = 0;
	int token_total = 0;

/* ------------------------------------------------------------------------------------------------ Rules */
#line 834 "prep_scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 35 "scanner.l"

#line 1023 "prep_scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 311 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 977 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "scanner.l"
{ return CONSTANT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "scanner.l"
{ return CONSTANT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "scanner.l"
{ return CONSTANT; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 39 "scanner.l"
{ return CONSTANT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "scanner.l"
{ return CONSTANT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "scanner.l"
{ return CONSTANT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "scanner.l"
{ return CONSTANT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "scanner.l"
{operators ++; token_total ++; strcpy(name,yytext); return SHLEQUAL;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return SHREQUAL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return PLUSPLUS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return MINUSMINUS;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return PLUSEQUAL;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return MINUSEQUAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return MULEQUAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return DIVEQUAL;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return MODEQUAL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return ANDEQUAL;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return OREQUAL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return ROOFEQUAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return ARROW;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return EQUAL;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return NOTEQUAL;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return AND;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return OR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return SHL;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return SHR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return LEQ; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return GEQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return LESSMORE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return ASSIGN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return PLUS;   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return MINUS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return MUL; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return DIV; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return BITAND;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return BITOR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return ROOF;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return TAIL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 76 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return MOD;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 77 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return LESS;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 78 "scanner.l"
{ operators ++; token_total ++;strcpy(name,yytext); return GREATER;}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 79 "scanner.l"
{ strcpy(name,yytext); return STRING;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 80 "scanner.l"
{ strcpy(name,yytext); return UNDERSCORE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "scanner.l"
{ strcpy(name,yytext); return SINGLEQUOTE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return LPAREN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return RPAREN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return CORCHL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return CORCHR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return LBRACKET;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return RBRACKET;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "scanner.l"
{ strcpy(name,yytext); return BACKSLASH;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "scanner.l"
{ strcpy(name,yytext);return COMMENTOPEN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "scanner.l"
{ strcpy(name,yytext);return COMMENTCLOSE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "scanner.l"
{ strcpy(name,yytext);return UNCLOSEDCOMMENT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return COLON;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "scanner.l"
{ strcpy(name,yytext); return QUESTIONMARK;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "scanner.l"
{ operators++; token_total ++; strcpy(name,yytext); return NOT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return SEMICOLON;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return COMMA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "scanner.l"
{ delimiters ++; token_total ++;strcpy(name,yytext); return PERIOD;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "scanner.l"
{ strcpy(name,yytext); return DOUBLEQUOTE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return IFSYS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return ELSESYS;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return WHILELOOP;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return FORLOOP;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return AUTO;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return BREAK;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return CASE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 109 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return CHAR;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 110 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return CONST;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 111 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return CONTINUE;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return DEFAULT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return DO;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return DOUBLE;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 116 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return ENUM;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 117 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return EXTERN;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return FLOAT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 119 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return GOTO;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 120 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return INT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return PRINTF;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return FPRINTF;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return FOPEN;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return FCLOSE;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return SYSTEM;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return STRCPY;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return STRCMP;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return EXIT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return TRUE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return FALSE;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 133 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return TOUPPER;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 134 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return FEOF;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 135 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return GETC;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 136 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return MEMSET;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 137 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return MALLOC;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 138 "scanner.l"
{palabras_reservadas ++; token_total ++; strcpy(name,yytext); return CALLOC;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return LONG;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return REGISTER;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 "scanner.l"
{ palabras_reservadas ++; token_total ++; return RETURN;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return SHORT;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return SIGNED;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return SIZEOF;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return STATIC;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 148 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return STRUCT;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 149 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return SWITCH;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 150 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return TYPEDEF;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 151 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return UNION;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return UNSIGNED;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 153 "scanner.l"
{ palabras_reservadas ++; token_total ++; strcpy(name,yytext); return VOID;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 154 "scanner.l"
{ palabras_reservadas ++; token_total ++;strcpy(name,yytext); return VOLATILE;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 156 "scanner.l"
{ strcpy(name,yytext); return EOF;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 157 "scanner.l"
{strcpy(name,yytext); return TAB;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 158 "scanner.l"
{ strcpy(name,yytext); return SPACE;}
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 159 "scanner.l"
{strcpy(name,yytext); return NEWLINE;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 161 "scanner.l"
{ identifiers ++; token_total ++; strcpy(name,yytext); return ID;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 162 "scanner.l"
{ literals ++; token_total ++; strcpy(name,yytext); return NUMBER;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 163 "scanner.l"
{ strcpy(name,yytext); return UNKNOWN;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 168 "scanner.l"
ECHO;
	YY_BREAK
#line 1703 "prep_scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 311 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 311 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 310);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 168 "scanner.l"


	/* --------------------------------------------------------------------------------------------------Code */

	void checkRegisteredTokens(){
		printf("PALABRAS RESERVADAS ---> %d\n", palabras_reservadas);
		printf("IDENTIFICADORES ---> %d\n", identifiers);
		printf("LITERALS ---> %d\n", literals);
		printf("OPERADORES ---> %d\n", operators);
		printf("DELIMITADORES ---> %d\n", delimiters);
		printf("token_total ---> %d\n", token_total);
	}

	void count_tokens(int pToken){
		if (isInserted(pToken)){
		}
		else{
			insertTokenType(pToken);
		}
	}

	bool isInserted(int pTokenType){
		int i = 0;
		bool isInserted = false;
		while(i<105){
			if(pTokenType == token_type[i]){
				isInserted = true;
				token_quantity[i] ++; 	//Actualizo la cantidad de types registrados
			}
			i++;
		}
		return isInserted;
	}

	void insertTokenType(int pTokenType){

		token_type[insertedTokens] = pTokenType;
		token_quantity[insertedTokens] ++;
		insertedTokens++;

	}

void toHex(FILE* file) {
	char outword[33];
	int i,len;
	len = strlen(yytext);
	for(i = 0; i<len; i++) {
		sprintf(outword + i * 2, "%02X", yytext[i]);
	}
	fprintf(file, " \\textcolor{Red}{%s}\n",  outword);
}

	void scanFile(){
		file = fopen( "processedFile.txt", "r" );
		YY_BUFFER_STATE bufferFinal = yy_create_buffer(file,YY_BUF_SIZE);
		estructura t ;


		//Presentación Beamer. Parte 1

		FILE* beamerFile = fopen( "beamerFile.tex", "w+" );
		int slide_lines = 0;
		int i;
		bool n_quote = true;
		int included_tokens = 0;
		int total_tkns = insertedTokens;





	  fprintf(beamerFile, "\\documentclass[8, usernames, dvipsnames]{beamer}\n");
		fprintf(beamerFile, "\\usepackage{color}\n");

		fprintf(beamerFile, "\\usepackage{pgfplots}\n");
		fprintf(beamerFile, "\\pgfplotsset{width=11.5cm,compat=1.9}\n");
		fprintf(beamerFile, "\\usepackage{dirtytalk}\n");
		fprintf(beamerFile, "\\usepackage[spanish]{babel}\n");
		fprintf(beamerFile, "\\usepackage[utf8]{inputenc}\n");

		fprintf(beamerFile, "\\usepackage{pgf-pie}\n");

		fprintf(beamerFile, "\\usetheme{Warsaw}\n");
		fprintf(beamerFile, "\\usecolortheme{spruce}\n");

	  fprintf(beamerFile, "\\setbeamercolor{itemize item}{fg=darkred!80!black}\n");




	  fprintf(beamerFile,"\\begin{document} \n");
	  fprintf(beamerFile, "\\title{\n");
		fprintf(beamerFile, "\\begin{Large}\n");
		fprintf(beamerFile, "TEC\n");
		fprintf(beamerFile, "\\end{Large}\n");
		fprintf(beamerFile, "\\newline\n");
		fprintf(beamerFile, "\\begin{Large}\n");
		fprintf(beamerFile, "\\\\Compiladores e Int\\'erpretes\n");
		fprintf(beamerFile, "\\\\Proyecto \\#2: Analizador L\\'exico\n");
		fprintf(beamerFile, "\\\\Profesor: Francisco Torres\n");
		fprintf(beamerFile, "\\end{Large}\n");
	  fprintf(beamerFile, "}\n");
	  fprintf(beamerFile, "\\author{Dennisse Rojas Casanova\n");
	  fprintf(beamerFile, "\\\\Treicy S\\'anchez Guti\\'errez}\n");
		fprintf(beamerFile, "\\date{25 de Mayo, 2016}\n");
	  fprintf(beamerFile,"\\maketitle \n");

		//Parte 1 :Flex y Scanner
	  fprintf(beamerFile,"\\begin{frame} \n");
	  fprintf(beamerFile,"\\frametitle{An\\'alisis L\\'exico y Flex} \n");
	  fprintf(beamerFile,"El An\\'alisis L\\'exico consiste en descomponer un fuente de entrada en categor\\'ias l\\'exicas m\\'inimas llamadas tokens.");
	  fprintf(beamerFile,"Un programa en Flex consiste b\\'asicamente en una lista de expresiones regulares que definen acciones a ejecutar cuando ocurre un match.");
	  fprintf(beamerFile,"\\end{frame} \n");
		fprintf(beamerFile, "\\begin{frame}\n");

		t = getNextToken(bufferFinal);
		while(t.token_type != EOF){
			if(slide_lines == 10) {
			fprintf(beamerFile, "\\end{frame}\n");
			fprintf(beamerFile, "\\begin{frame}\n");
			slide_lines = 0;
			}

			switch(t.token_type){
				case NUMBER:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "SeaGreen", t.value);
					break;
				//Operadores Lógicos
				case AND:
					fprintf(beamerFile, "\\textcolor{%s}{ \\%c\\%c }\n", "Goldenrod", yytext[0], yytext[1]);
					break;
				case OR:
					fprintf(beamerFile, "\\textcolor{%s}{ $%s$ }\n", "Goldenrod", t.value);
					break;
				case NOT:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "Goldenrod", t.value);
					break;

				//Operadores Aritméticos

				case PLUS:
				case MINUS:
				case MUL:
				case DIV:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "SpringGreen", t.value);
					break;

				case IFSYS:
				case ELSESYS:
				case WHILELOOP:
				case FORLOOP:
				case AUTO:
				case BREAK:
				case CASE:
				case CHAR:
				case CONST:
				case CONTINUE:
				case DEFAULT:
				case DO:
				case DOUBLE:
				case ENUM:
				case EXTERN:
				case FLOAT:
				case GOTO:
				case INT:
				case LONG:
				case REGISTER:
				case RETURN:
				case SHORT:
				case SIGNED:
				case SIZEOF:
				case STATIC:
				case STRUCT:
				case SWITCH:
				case TYPEDEF:
				case UNION:
				case UNSIGNED:
				case VOID:
				case VOLATILE:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OrangeRed", t.value);
					break;

				case TAB:
					fprintf(beamerFile, "\\textcolor{%s}{\\%s }\n", "White", "  " );
					break;
				case SPACE:
					fprintf(beamerFile, "\\textcolor{%s}{\\ }\n", "White");
					break;
				case NEWLINE:
					fprintf(beamerFile, "\n ");
					slide_lines++;
					break;

				case FPRINTF:
				case PRINTF:
				case FOPEN:
				case FCLOSE:
				case MALLOC:
				case SYSTEM:
				case CALLOC:
				case STRCPY:
				case STRCMP:
				case EXIT:
				case TRUE:
				case FALSE:
				case TOUPPER:
				case FEOF:
				case GETC:
				case MEMSET:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OrangeRed", t.value);
					break;


				case COLON:
	 			case SEMICOLON:
	 			case COMMA:
	 			case PERIOD:
	 			case QUESTIONMARK:
	 				fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "Sepia", t.value);
	 				break;
	 			case UNDERSCORE:
	 				fprintf(beamerFile, "\\textcolor{%s}{\\%s}\n", "Sepia", t.value);
	 				break;

				case BACKSLASH:
					fprintf(beamerFile, "\\textcolor{%s}{%s }\n", "Gray", "\\textbackslash");
					break;
					case ASSIGN:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "Salmon", t.value);
					break;


				//PARENTHESES
				case LPAREN:
				case RPAREN:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "SkyBlue", t.value);
					break;
				case CORCHR:
				case CORCHL:
					fprintf(beamerFile, "\\textcolor{%s}{\\%s }\n", "SkyBlue", t.value);
					break;
				case LBRACKET:
				case RBRACKET:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "SkyBlue", t.value);
					break;

				case SINGLEQUOTE:
	 				fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "BurntOrange", t.value);
	 				break;
	 			case DOUBLEQUOTE:
	 				fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "BurntOrange", t.value);
	 				break;
				case MOD:
					fprintf(beamerFile, "\\textcolor{%s}{\\%s}\n", "Apricot", t.value);
					break;

				case SHLEQUAL:
				case SHREQUAL:
				case PLUSPLUS:
				case MINUSMINUS:
				case PLUSEQUAL:
				case MINUSEQUAL:
				case MULEQUAL:
				case DIVEQUAL:
				case MODEQUAL:
				case ANDEQUAL:
				case OREQUAL:
				case ROOFEQUAL:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "Apricot", t.value);
					break;
				case EQUAL:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OliveGreen", "$==$");
					break;
				case NOTEQUAL:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OliveGreen", "$!=$");
					break;
				case LEQ:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OliveGreen", "\\textless =");
					break;
				case GEQ:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OliveGreen", "\\textgreater =");
					break;
				case LESS:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OliveGreen", "\\textless");
					break;
				case GREATER:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OliveGreen", "\\textgreater");
					break;
				case LESSMORE:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "OliveGreen", "\\textless\\textgreater");
					break;


				case ARROW:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "Fuchsia", "-\\textgreater");
					break;
				case TAIL:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "MidnightBlue", "\\textasciitilde");
					break;
				case BITAND:
				case BITOR:
				case ROOF:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "MidnightBlue", "\\textasciicircum");
					break;
				case SHL:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "MidnightBlue", "\\textless\\textless");
					break;
				case SHR:
					fprintf(beamerFile, "\\textcolor{%s}{%s}\n", "MidnightBlue", "\\textgreater\\textgreater");
					break;

				case ID:

					i = 0;
					fprintf(beamerFile, "\\textcolor{%s}{", "Violet");
					while(i < yyleng) {
						if (yytext[i] == '_') {
							fprintf(beamerFile, "\\_");
						} else {
							fprintf(beamerFile, "%c", yytext[i]);
						}
						i++;
					}

					fprintf(beamerFile, "}");
					break;
				case STRING:
					n_quote = true;
					i = 1;
					fprintf(beamerFile, "\\textcolor{%s}{\\say{", "Orchid");
					while(n_quote) {

						if(yytext[i] == '"'){
							n_quote = false;
						} else if(yytext[i] == '|'){
							fprintf(beamerFile, " $\%c$ ", yytext[i]);
						} else if(yytext[i] == '{' || yytext[i] == '}' || yytext[i] == '%' || yytext[i] == '&' || yytext[i] == '#' || yytext[i] == '_') {
							fprintf(beamerFile, " \\%c ", yytext[i]);
						} else if(yytext[i] == '\\') {
							fprintf(beamerFile, " \\%s ", "textbackslash ");
						} else if(yytext[i] == '~') {
							fprintf(beamerFile, " \\%s ", "textasciitilde ");
						} else if(yytext[i] == '<') {
							fprintf(beamerFile, " \\%s ", "textless ");
						} else if(yytext[i] == '>') {
							fprintf(beamerFile, " \\%s ", "textgreater ");
						} else if(yytext[i] == '^') {
							fprintf(beamerFile, " \\%s ", "textasciicircum ");
						} else {
							fprintf(beamerFile, "%c", yytext[i]);
						}
						i++;
					}
					fprintf(beamerFile, "}}\n");
					break;
					case CHARACTER:
						n_quote = true;
						i = 1;
						fprintf(beamerFile, "\\textcolor{%s}{\\lq ", "BrickRed");
						while(n_quote) {

							if(yytext[i] == '\''){
								n_quote = false;
							} else if(yytext[i] == '|'){
								fprintf(beamerFile, " $\%c$ ", yytext[i]);
							} else if(yytext[i] == '{' || yytext[i] == '}' || yytext[i] == '%' || yytext[i] == '&' || yytext[i] == '#' || yytext[i] == '_') {
								fprintf(beamerFile, " \\%c ", yytext[i]);
							} else if(yytext[i] == '\\') {
								fprintf(beamerFile, " \\%s ", "textbackslash");
							} else if(yytext[i] == '~') {
								fprintf(beamerFile, " \\%s ", "textasciitilde");
							} else if(yytext[i] == '<') {
								fprintf(beamerFile, " \\%s ", "textless");
							} else if(yytext[i] == '>') {
								fprintf(beamerFile, " \\%s ", "textgreater");
							} else if(yytext[i] == '^') {
								fprintf(beamerFile, " \\%s ", "textasciicircum");
							} else {
								fprintf(beamerFile, "%c", yytext[i]);
							}
							i++;
						}
						fprintf(beamerFile, "\\rq}\n");
						break;
					case UNKNOWN:
						toHex(beamerFile);
						break;

				}
				t = getNextToken(bufferFinal);
		}
		fprintf(beamerFile, "\\end{frame}\n");

		//*************************Histograma**************************************





		fprintf(beamerFile,"\\begin{frame} \n");

		fprintf(beamerFile,"\\begin{tikzpicture} \n");
		fprintf(beamerFile,"\\begin{axis}[ \n");

		fprintf(beamerFile,"symbolic x coords={Reservadas, Identificadores,Literales,Operadores, Delimitadores},xtick=data,xticklabel style={anchor=base,yshift=-\\baselineskip},\n");
		fprintf(beamerFile,"nodes near coords={\\pgfmathprintnumber\\pgfplotspointmeta}\n");



		fprintf(beamerFile,"]\n");

		fprintf(beamerFile,"\\addplot[ybar,fill=Turquoise]  \n");
		fprintf(beamerFile,"coordinates {\n");

		fprintf(beamerFile, "(%s,", "Reservadas");
		fprintf(beamerFile, "%d)", palabras_reservadas);
		fprintf(beamerFile, "(%s,", "Identificadores");
		fprintf(beamerFile, "%d)",identifiers);
		fprintf(beamerFile, "(%s,", "Literales");
		fprintf(beamerFile, "%d)", literals);
		fprintf(beamerFile, "(%s,", "Operadores");
		fprintf(beamerFile, "%d)", operators);
		fprintf(beamerFile, "(%s,", "Delimitadores");
		fprintf(beamerFile, "%d)", delimiters);
		fprintf(beamerFile,"};\n");


		fprintf(beamerFile,"\\end{axis}\n");
		fprintf(beamerFile,"\\end{tikzpicture}\n");
		fprintf(beamerFile,"\\end{frame} \n");

		//************************Pie

		fprintf(beamerFile,"\\begin{frame} \n");

		fprintf(beamerFile,"\\begin{tikzpicture}\n");
		fprintf(beamerFile,"\\pie[rotate = 180]\n");
		fprintf(beamerFile,"{%.2lf",(100 * palabras_reservadas)/((double)token_total));
		fprintf(beamerFile,"/Palabras Reservadas,\n");
		fprintf(beamerFile,"%.2lf",(100 * identifiers)/((double)token_total));
		fprintf(beamerFile,"/Identificadores,\n");
		fprintf(beamerFile,"%.2lf",(100 * literals)/((double)token_total));
		fprintf(beamerFile,"/Literales,\n");
		fprintf(beamerFile,"%.2lf",(100 * operators)/((double)token_total));
		fprintf(beamerFile,"/Operadores,\n");
		fprintf(beamerFile,"%.2lf",(100 * delimiters)/((double)token_total));
		fprintf(beamerFile,"/Delimitadores}\n");


		fprintf(beamerFile,"\\end{tikzpicture}\n");

		fprintf(beamerFile,"\\end{frame} \n");

		//Final del Archivo

		fprintf(beamerFile,"\\end{document}");
		fclose(beamerFile);
		system("pdflatex beamerFile.tex");
		system("evince beamerFile.pdf");

	}



	estructura getNextToken(YY_BUFFER_STATE buffer){
		yy_switch_to_buffer (buffer); // Nos pasamos al buffer principal.
		int next_token = yylex();
		if (next_token == COMMENTOPEN){
			printf("Encontre el inicio d un comment!\n");
			while(next_token != COMMENTCLOSE){
				next_token = yylex();
			}
			printf("Encontre el final del comment %s\n", name);
			next_token = yylex();
		}
		if(next_token == UNCLOSEDCOMMENT){
			while(next_token != NEWLINE){
				next_token = yylex();
			}
			next_token = yylex();
		}
		estructura identifiedToken;
		identifiedToken.token_type = next_token;
		strcpy(identifiedToken.value,name);

		printf("%s", identifiedToken.value);
		return identifiedToken;
	}

